version: '3'
services:
  golang:
    container_name: golang
    build: .
    ports:
      - 8101:8101
      - 50051:50051/tcp
    networks:
      - backend
    volumes:
      - .:/usr/app
  mongo: 
    container_name: mongo
    build: 
      context: ../../mongodb
      dockerfile: Dockerfile
    volumes:
      - ./data/db:/data/db
    image: mongo  
    ports:
       - 27017:27017
    networks:
      - backend      
networks:
  backend:
    driver: bridge