version: '3'
services:
  mongo: 
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    image: mongo  
    ports:
       - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
