version: '3'
services:
  ui:
    container_name: ui
    build: .
    networks:
      - backend
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    depends_on:
      - "golang"
networks:
  backend:
    driver: bridge
